### PR TITLE
fix: improve search box

### LINKED ISSUE #136: 收藏功能优化
1、应用的集群列表，支持收藏
2、搜索历史记录，改成搜索记录
3、优化集群标签和搜索条件一致，比如性能环境，现在搜索框过滤条件是perf
4、输入条件，点击enter 搜索后，下拉框要隐藏一下
5、搜索输入框，用户输入的内容下拉框不能匹配的，就把下拉框隐藏了

### PR DESCRIPTION
**Pull request by kilosonc**
Fix: https://github.com/horizoncd/horizon/issues/136

### CODE REVIEW

File: src/components/FilterBox/Suggestions.tsx [hunk 1]
```diff
@@ -67,7 +66,9 @@ const Suggestions = React.forwardRef((props: PropsWithChildren<SuggestionProps>,
             </span>
           )
           : null}
-        <QueryBoldSpan query={query}>{item.name ?? ''}</QueryBoldSpan>
```
Comment (xuzhu-591) [inline src/components/FilterBox/Suggestions.tsx]: why remove bold style?

File: src/components/FilterBox/Tag.tsx
Comment (xuzhu-591) [inline src/components/FilterBox/Tag.tsx:1]: The component's imports should be fixed.

File: src/pages/applications/Clusters/v2/index.tsx
Comment (xuzhu-591) [inline src/pages/applications/Clusters/v2/index.tsx:1]: v2 also supports collections ?

**Review by xuzhu-591 — APPROVED** [review]
